### ISSUE TITLE
WARNING: tokenization mismatch: 2 vs. 89. (ignored)

### ISSUE THREAD

**Issue by Liuziyu77** [RifleZhang/LLaVA-Hound-DPO#9]
When I am trying to use multi-images data to tune a llava-v1.5-7B, it reports "WARNING: tokenization mismatch: 2 vs. 89. (ignored)". That's why?

**Comment by RifleZhang** [comment]
I think the error happens because of tokenization error. I would suggest checking:

1. The version of transformers (we used transformers==4.36.2)
2. The selection of conversation [template](https://github.com/RifleZhang/LLaVA-Hound-DPO/blob/main/llava_hound_dpo/llava/conversation.py#L361)
3. In your training data, make sure to have special token like <video> or [<image>](https://github.com/RifleZhang/LLaVA-Hound-DPO/blob/main/llava_hound_dpo/llava/train/train.py#L543) in the prompt.

Maybe you can start with our released data for debugging, and then move forward with customized data.

Let me know if you still encounter the same error.
